server:
  port: 8080
dubbo:
  application:
    name: good-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    host: localhost
    port: 20880
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sgmall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456